#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 10 12:29:11 WEST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Tostadora.zip
enableShaders=false
