#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 10 16:38:35 WEST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Ultra.zip
enableShaders=true
